services:
  app:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/notes-app
      - PORT 3001
   
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

